/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/**
 *
 * @author Invitado
 */
public class Ayuda extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda
     */
    public Ayuda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVolverAMenuPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        intruccionesDeAyuda = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 620));
        setMinimumSize(new java.awt.Dimension(500, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVolverAMenuPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        botonVolverAMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botonVolverAMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 2.png"))); // NOI18N
        botonVolverAMenuPrincipal.setText("MENU PRINCIPAL");
        botonVolverAMenuPrincipal.setContentAreaFilled(false);
        botonVolverAMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonVolverAMenuPrincipal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 2.png"))); // NOI18N
        botonVolverAMenuPrincipal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 1.png"))); // NOI18N
        botonVolverAMenuPrincipal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonVolverAMenuPrincipal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonVolverAMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolverAMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 200, 100));

        intruccionesDeAyuda.setColumns(20);
        intruccionesDeAyuda.setRows(5);
        intruccionesDeAyuda.setText("PARA INFORMACION ACERCA DEL PROGRAMA POR FAVOR COMUNICARSE CON LOS \nDESARROLLADORES DEL PRESENTE. \nNOS PUEDE ENCONTRAR EN NUESTRAS CASAS, O A LA SALIDA DE LA U. POR FAVOR NO MOLESTAR \nCUANDO ESTEMOS OCUPADOS. GRACIAS POR SU ATENCION Y USO DEL PROGRAMA\nQUE TENGA BUENA NOCHE O DIA, O EN LO QUE SEA QUE ESTE.");
        intruccionesDeAyuda.setEnabled(false);
        jScrollPane1.setViewportView(intruccionesDeAyuda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 520, 390));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instrucciones");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAMenuPrincipalActionPerformed
        //CON ESTA LINEA DE CODIGO SE REGRESARA AL MENU PRINCIPAL
        if(evt.getSource() ==  botonVolverAMenuPrincipal){
        MenuPrincipal mensajero = new MenuPrincipal();
        this.setVisible(false);
        mensajero.setVisible(true);
        }
    }//GEN-LAST:event_botonVolverAMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverAMenuPrincipal;
    private javax.swing.JTextArea intruccionesDeAyuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
