package clases;

import controller.ClienteController;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author Invitado
 */
public class VistaCliente extends javax.swing.JFrame {

    ClienteController clientco = new ClienteController();

    DefaultTableModel tabla = new DefaultTableModel();

    int index_actual = 0;

    public VistaCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        String[] cabecera = new String[]{"ID Cliente", "Nombre", "Apellido", "Telefono", "Dirección"};
        tabla.setColumnIdentifiers(cabecera);
        tablaClientes.setModel(tabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonAyuda = new javax.swing.JButton();
        botonAtrasControlDeCartera = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        leyendaRegistroDeCliente = new javax.swing.JLabel();
        idclienteJLabel = new javax.swing.JLabel();
        nombreclienteJLabel = new javax.swing.JLabel();
        apellidoclienteJLabel = new javax.swing.JLabel();
        telclienteJLabel = new javax.swing.JLabel();
        dirclienteJLabel = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_apellidoCliente = new javax.swing.JTextField();
        txt_telCliente = new javax.swing.JTextField();
        txt_dirCliente = new javax.swing.JTextField();
        txt_Cliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAgregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteagregar2.png"))); // NOI18N
        botonAgregar.setText("AGREGAR");
        botonAgregar.setContentAreaFilled(false);
        botonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteagregar2.png"))); // NOI18N
        botonAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteagregar1.png"))); // NOI18N
        botonAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 137));

        botonConsultar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonConsultar.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientebuscar2.png"))); // NOI18N
        botonConsultar.setText("CONSULTAR");
        botonConsultar.setContentAreaFilled(false);
        botonConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonConsultar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientebuscar2.png"))); // NOI18N
        botonConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientebuscar1.png"))); // NOI18N
        botonConsultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 160, 137));

        botonEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeliminar2.png"))); // NOI18N
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setContentAreaFilled(false);
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeliminar2.png"))); // NOI18N
        botonEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeliminar1.png"))); // NOI18N
        botonEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, 137));

        botonModificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeditar2.png"))); // NOI18N
        botonModificar.setText("MODIFICAR");
        botonModificar.setContentAreaFilled(false);
        botonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonModificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeditar2.png"))); // NOI18N
        botonModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteeditar1.png"))); // NOI18N
        botonModificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 140));

        botonAyuda.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonAyuda.setForeground(new java.awt.Color(255, 255, 255));
        botonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda 2.png"))); // NOI18N
        botonAyuda.setText("AYUDA");
        botonAyuda.setContentAreaFilled(false);
        botonAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAyuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda 1.png"))); // NOI18N
        botonAyuda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda 2.png"))); // NOI18N
        botonAyuda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(botonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, 130));

        botonAtrasControlDeCartera.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonAtrasControlDeCartera.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasControlDeCartera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 2.png"))); // NOI18N
        botonAtrasControlDeCartera.setText("ATRAS");
        botonAtrasControlDeCartera.setContentAreaFilled(false);
        botonAtrasControlDeCartera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasControlDeCartera.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 1.png"))); // NOI18N
        botonAtrasControlDeCartera.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras 2.png"))); // NOI18N
        botonAtrasControlDeCartera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAtrasControlDeCartera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(botonAtrasControlDeCartera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 100));

        tablaClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaClientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 630, 250));

        leyendaRegistroDeCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        leyendaRegistroDeCliente.setText("REGISTRO DE CLIENTE");
        jPanel1.add(leyendaRegistroDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        idclienteJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        idclienteJLabel.setText("ID:");
        jPanel1.add(idclienteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        nombreclienteJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        nombreclienteJLabel.setText("Nombre:");
        jPanel1.add(nombreclienteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        apellidoclienteJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        apellidoclienteJLabel.setText("Apellido:");
        jPanel1.add(apellidoclienteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        telclienteJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        telclienteJLabel.setText("Telefono:");
        jPanel1.add(telclienteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        dirclienteJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        dirclienteJLabel.setText("Dirección:");
        jPanel1.add(dirclienteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));
        jPanel1.add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1));
        jPanel1.add(txt_apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, -1));
        jPanel1.add(txt_telCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 130, -1));
        jPanel1.add(txt_dirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 120, -1));
        jPanel1.add(txt_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        if (txt_Cliente.getText().equals("") || txt_nombreCliente.getText().equals("") || txt_apellidoCliente.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Advertencia\nCampo vacio");

        } else {
            clientco.create(new Cliente(
                    txt_Cliente.getText(),
                    txt_nombreCliente.getText(),
                    txt_apellidoCliente.getText(),
                    txt_telCliente.getText(),
                    txt_dirCliente.getText()));
            ListarTodos();
            txt_Cliente.setText("");
            txt_nombreCliente.setText("");
            txt_apellidoCliente.setText("");
            txt_telCliente.setText("");
            txt_dirCliente.setText("");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(index_actual >= 0){
    
        clientco.delete(index_actual);
        ListarTodos();
                
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed


    }//GEN-LAST:event_botonConsultarActionPerformed
//Aqui selecciono la posicion de la fila de la tabla de Clientes...
    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        index_actual = tablaClientes.getSelectedRow();
        System.out.println(clientco.getClientes().get(index_actual).getNombre());
    }//GEN-LAST:event_tablaClientesMouseClicked

    public void ListarTodos() {

        listarClientes((DefaultTableModel) tablaClientes.getModel(), clientco.getClientes());
    }

    public void listarClientes(DefaultTableModel tabla, ArrayList<Cliente> arr) {
        tabla.setNumRows(0);
        for (int i = 0; i < arr.size(); i++) {
            Cliente tm = arr.get(i);
            tabla.addRow(new Object[]{
                tm.getID(),
                tm.getNombre(),
                tm.getApellido(),
                tm.getTelefono(),
                tm.getDireccion()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoclienteJLabel;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtrasControlDeCartera;
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JLabel dirclienteJLabel;
    private javax.swing.JLabel idclienteJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel leyendaRegistroDeCliente;
    private javax.swing.JLabel nombreclienteJLabel;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JLabel telclienteJLabel;
    private javax.swing.JTextField txt_Cliente;
    private javax.swing.JTextField txt_apellidoCliente;
    private javax.swing.JTextField txt_dirCliente;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_telCliente;
    // End of variables declaration//GEN-END:variables
}
